
# Monitors
source = ~/.config/hypr/conf/monitors.conf

# Core
source = ~/.config/hypr/conf/general.conf
source = ~/.config/hypr/conf/decoration.conf
source = ~/.config/hypr/conf/animations.conf
source = ~/.config/hypr/conf/input.conf

# Behaviour
source = ~/.config/hypr/conf/keybinds.conf
source = ~/.config/hypr/conf/windowrules.conf
source = ~/.config/hypr/conf/workspaces.conf
source = ~/.config/hypr/conf/autostart.conf
source = ~/.config/hypr/conf/env.conf
source = ~/.config/hypr/conf/plugins.conf

$terminal = kitty
$fileManager = kitty -e yazi
$menu = rofi -show drun
$mainMod = SUPER

