background {
  monitor =
  path = ~/tapety/oregonl.jpg
  blur_passes = 3
  blur_size = 7
  brightness = 0.75
  vibrancy = 0.17
}

label {
  monitor =
  text = cmd[update:1000] echo "$TIME"
  font_size = 72
  font_family = JetBrains Mono
  color = rgba(255, 255, 255, 0.85)
  position = 0, 80
  halign = center
  valign = center
}

input-field {
  monitor =
  size = 280, 52
  outline_thickness = 2
  outer_color = rgba(255,255,255,0.2)
  inner_color = rgba(0,0,0,0.5)
  font_color = rgb(255,255,255)
  placeholder_text = <i>Password</i>
  dots_size = 0.25
  position = 0, -120
  halign = center
  valign = center
}
