exec-once = awww-daemon
exec-once = waybar
exec-once = swaync
exec-once = awww img /home/yaushi/tapety/mood.jpg --transition-type fade --transition-duration 1
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = /opt/Mullvad VPN/mullvad-vpn