decoration {
    rounding = 12
    rounding_power = 2
    active_opacity = 1.0
    inactive_opacity = 1.0
    fullscreen_opacity = 1.0

    shadow {
        enabled = true
        range = 20
        render_power = 3
        color = rgba(0d121088)
        color_inactive = rgba(0d121044)
        offset = 0, 4
    }

    blur {
        enabled = true
        size = 6
        passes = 3
        new_optimizations = true
        xray = false
        ignore_opacity = false
        popups = true
    }
}